version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:43"
    commit-message:
      include: scope
      prefix: "[MNT] "
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      python-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:43"
    commit-message:
      include: scope
      prefix: "[MNT] "
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
