"""Lazily loaded, cached, canonical FCA schedule metadata.

The metadata itself is generated by ``scripts/generate_fca_schedule_metadata.py``
from FCA's real, published archives, hand-correctable via that script's
override mechanism, and shipped as one JSON file per schedule under
``call_report/fca/data/schedules/`` -- see that script's module docstring
for the full generation pipeline. This module is just the runtime read
side: each file is parsed at most once per process, on first request.
"""

from __future__ import annotations

import functools
import importlib.resources
from collections.abc import Mapping

from call_report.core import FileMetadata
from call_report.fca.enums import FCASchedule
from call_report.fca.institutions import INSTITUTIONS_ROOT


def _load_file_metadata(*, root: str) -> FileMetadata:
    """Read and parse one root's shipped, canonical FileMetadata JSON.

    Shared by `get_fca_file_metadata` and `get_institutions_file_metadata`,
    which are the ones responsible for caching -- this helper always
    re-reads.

    Parameters
    ----------
    root : str
        The schedule root name, e.g. ``"RCB"``, or `INSTITUTIONS_ROOT`.

    Returns
    -------
    FileMetadata
        The parsed metadata.
    """
    resource = importlib.resources.files("call_report.fca").joinpath(
        "data", "schedules", f"{root}.json"
    )
    return FileMetadata.from_json(text=resource.read_text(encoding="utf-8"))


@functools.cache
def get_fca_file_metadata(*, schedule: FCASchedule) -> FileMetadata:
    """Return the canonical FileMetadata for one FCA schedule.

    Parsed from the packaged JSON on first call for `schedule`, then
    cached for the life of the process -- no repeated parsing.

    Parameters
    ----------
    schedule : FCASchedule
        The schedule to return metadata for.

    Returns
    -------
    FileMetadata
        `schedule`'s canonical, cross-time field metadata.

    Examples
    --------
    >>> from call_report.fca import FCASchedule, get_fca_file_metadata
    >>> metadata = get_fca_file_metadata(schedule=FCASchedule.RCB)
    >>> metadata.name
    'RCB'
    >>> metadata.first_period.label
    '2000Q1'
    >>> "UNINUM" in metadata.file_schema
    True
    """
    return _load_file_metadata(root=schedule.value)


@functools.cache
def get_institutions_file_metadata() -> FileMetadata:
    """Return the canonical FileMetadata for the FCA institution roster.

    The institution roster (root name `INSTITUTIONS_ROOT`) isn't a
    `FCASchedule` member -- see `call_report.fca.institutions` -- so it
    gets its own loader rather than being reachable through
    `get_fca_file_metadata`.

    Returns
    -------
    FileMetadata
        The roster's canonical, cross-time field metadata.

    Examples
    --------
    >>> from call_report.fca import get_institutions_file_metadata
    >>> metadata = get_institutions_file_metadata()
    >>> metadata.name
    'INST'
    """
    return _load_file_metadata(root=INSTITUTIONS_ROOT)


def all_fca_file_metadata() -> Mapping[FCASchedule, FileMetadata]:
    """Return every FCA schedule's canonical FileMetadata, keyed by FCASchedule.

    A convenience for callers that want every schedule's metadata at once
    rather than looking each one up individually via `get_fca_file_metadata`.

    Returns
    -------
    Mapping[FCASchedule, FileMetadata]
        Every `FCASchedule` member mapped to its metadata.

    Examples
    --------
    >>> from call_report.fca import FCASchedule, all_fca_file_metadata
    >>> metadata_by_schedule = all_fca_file_metadata()
    >>> len(metadata_by_schedule) == len(FCASchedule)
    True
    >>> metadata_by_schedule[FCASchedule.RCB].name
    'RCB'
    """
    return {
        schedule: get_fca_file_metadata(schedule=schedule) for schedule in FCASchedule
    }
