#!/usr/bin/env bash
set -euo pipefail

# Regenerate the committed requirements files from pyproject.toml.
#
# One file per dependency group, so each says what its name promises:
#
#   requirements.txt       [project] dependencies only, which is what the
#                          package needs at runtime. Currently just narwhals.
#   requirements-dev.txt   the dev extra: the test and lint toolchain, plus
#                          the pandas, polars, and pyarrow backends the
#                          suite exercises.
#   requirements-docs.txt  the docs extra: the sphinx stack.
#
# Together they cover every extra, so auditing all three (see
# .github/workflows/security.yml) scans the same package set a single
# --all-extras file would.
#
# --no-header omits pip-compile's "autogenerated with Python X.Y" banner.
# Without it the committed files record whichever interpreter last ran this
# script, so a contributor on 3.11 and CI on 3.12 produce files that differ
# only in that line and the drift check fails on nothing real.
#
# --strip-extras is the pip-tools 8.0 default. Setting it now keeps the
# output stable across that upgrade rather than letting it silently change
# the committed files and fail the drift check.
#
# pip-compile reuses the pins already present in an output file when they
# still satisfy pyproject.toml, so regenerating does not churn versions on
# unrelated changes. Pass --upgrade to this script to deliberately refresh
# them.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v pip-compile >/dev/null 2>&1; then
    echo "Error: pip-compile not found. Install pip-tools first (pip install pip-tools)." >&2
    exit 1
fi

compile() {
    pip-compile pyproject.toml --no-header --strip-extras "$@"
}

compile --output-file=requirements.txt "$@"
compile --extra dev --output-file=requirements-dev.txt "$@"
compile --extra docs --output-file=requirements-docs.txt "$@"

echo "Generated requirements.txt, requirements-dev.txt and requirements-docs.txt"
